### ISSUE TITLE
Issues with setup

### ISSUE THREAD

**Issue by gesslar** [oestrich/grapevine#151]
I want to help contribute to the web client, and I guess this is the only way to get it running.

So I followed the instructions laid out. I have all the deps installed.

Under Setup, when I get to `yarn --cwd assets`, I get:
```
gesslar@LIAM:~/git/grapevine/apps/grapevine$ yarn --cwd assets
Usage: yarn [options]

yarn: error: no such option: --cwd
```

I'm not really sure what the above is supposed to do, so I powered on anyway, and tried to run `mix ecto.reset` and got the following results:
```bash
gesslar@LIAM:~/git/grapevine/apps/grapevine$ mix ecto.reset

23:45:53.952 [error] GenServer #PID<0.417.0> terminating
** (RuntimeError) connect raised KeyError exception: key :password not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (elixir) lib/keyword.ex:393: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:720: Postgrex.Protocol.auth_md5/4
    (postgrex) lib/postgrex/protocol.ex:577: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for GrapevineData.Repo couldn't be dropped: killed
```

This all seems like a lot to just work on the client. Am I doing something wrong?

**Comment by oestrich** [comment]
Instead of that yarn option you can also `cd assets && yarn install && cd ..`

As it stands now you need to set up the entire application in order for the web client to work, it's all tied together due to the server-side component.

The issue with ecto is likely because you don't have a super user named as your `whoami` with ident authentication. You can make `config/dev.local.exs` with the following in it to suit your postgres set up.

```elixir
config :grapevine_data, GrapevineData.Repo,
  database: "grapevine_dev",
  hostname: "localhost",
  username: "changeme",
  password: "changeme",
  pool_size: 10,
  log: false
  ```

Hopefully those are your only two issues. I haven't done any elixir upgrades recently so there might be other small problems.
